adminPassword: "admin" # Change in production
service:
  type: LoadBalancer

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# You can inject custom dashboards via ConfigMaps
# dashboardsConfigMaps:
#   default: "grafana-dashboards-custom"
