apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: devops-demo.local # Replace with your domain
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: devops-demo-svc
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-frontend-svc
            port:
              number: 80
