apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  # Internal Kubernetes DNS path to the MongoDB service we just created
  MONGO_URI: "mongodb://mongodb-service:27017/medical-shop"
